config/routes.rb
Rails.application.routes.draw do
  

  get 'hello_world/index'

  root 'hello_world#index'
  
  get "kirjaudu" => "sessions#new", :as => "log_in"
  get "kirjaudu/ulos" => "sessions#destroy", :as => "log_out"
  get "rekisteröidy" => "users#new", :as => "sign_up"
  
  resources :users, :sessions
  
  get "articles/more" => "articles#more", :as => "articles_more"
  resources :articles do
    resources :comments
  end
  
  
  match 'telegram' => 'telegram#index', via: [:get, :post]
  get 'telegram/setup' => 'telegram#setup'
  get 'telegram/connect' => 'telegram#connect'
  get 'telegram/disconnect' => 'telegram#disconnect'
  get 'telegram/repair' => 'telegram#repair'
  
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  
  #Return a formatted date from an article
  def get_date
    date = created_at.to_date.strftime("Julkaistu %-d.%-m.%Y")
    if updated_at != created_at
      date += updated_at.to_date.strftime(" ja muokattu viimeksi %-d.%-m.%Y.")
    else
      date += "."
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = Article.find(params[:id])
  end
  
  def edit
    @article = Article.find(params[:id])
  end
  
  def update
    if current_user && current_user.privileges >= User.priv_level_writer
      @article = Article.find(params[:id])
      @article.update article_params
      redirect_to @article
    else
      not_privileged
    end
  end
  
  def create
    if current_user && current_user.privileges >= User.priv_level_writer
      @article = Article.new(article_params)
      
      @article.save
      redirect_to @article
    else
      not_privileged
    end
  end
  
  @@max_articles = 8
  
  def index
    @articles = Article.order(created_at: :desc).limit(@@max_articles)
    @depth = @@max_articles
    # true if articles clipped off
    @cut = Article.count > @depth
  end
  
  def destroy
    if current_user && current_user.privileges >= User.priv_level_writer
      @article = Article.find(params[:id])
      @article.destroy
      redirect_to articles_path
    else
      not_privileged
    end
  end
  
  def more
    old_depth = params[:depth].to_i
    new_depth = old_depth + @@max_articles
    
    @articles = Article.order(created_at: :desc).offset(old_depth).limit(@@max_articles)
    @cut = Article.count > new_depth
    @load_more_path = articles_more_url(:depth => new_depth)
    
    respond_to do |format|
      format.html { render :partial => "more" }
    end
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
  
  def not_privileged
    redirect_to root_url, :notice => "Sinulla ei ole oikeutta tehdä tätä."
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_editform.html.erb
<%# A partial for editing an article (form_for :article |f|, only render inside form!) %>
  <%= f.label :title, "Otsikko:" %><br/>
  <%= f.text_field :title %><br/>

  <%= f.label :text, "Leipäteksti:" %><br/>
  <%= f.text_area :text %><br/>

  <%= f.submit "Tallenna artikkeli" %>

app/views/articles/_more.html.erb
<% @articles.each do |article| %>
  <%= render "/articles/render", :article => article, :do_truncation => true %>
<% end %>

<dataset
  class="load_more_articles_path"
  data-load-more-path="<%= @load_more_path %>"
  <%= 'data-is-cut="true"' if @cut %>
/>

app/views/articles/_render.html.erb
<span class="article">
  <h2 id="article<%= article.id.to_s %>">
    <%= link_to article.title, article, { :class => "link_title" } %>
  </h2>
  <span class="text">
    <%= GitHub::Markdown.render_gfm(
      unless defined? do_truncation
        article.text
      else
        truncate(article.text, length: 1024, separator: ' ') {
          link_to "Lue koko artikkeli", article, { class: "read_whole" }
        }
      end
    ).html_safe %>
  </span>
  &nbsp;
  
  <span class="bottom_container">
    <%= article.get_date %>
    <% if current_user && current_user.privileges >= User.priv_level_writer %>
      <%= link_to("MUOKKAA", edit_article_path(article), { class: "action" }) %>
      <%= link_to "POISTA", article_path(article), method: :delete, class: "action",
       data:
        { confirm: 'Oletko aivan varma että haluat poistaa artikkelin "'+ article.title + '"?' }
      %>
    <% end %>
  </span>
  <br/>
  <hr>
</span>

app/views/articles/edit.html.erb
<% if current_user && current_user.privileges >= User.priv_level_writer %>
  <%# Logged in & privileged enough to edit an article %>
  <h1>Muokkaa artikkelia</h1>
  <%= form_for @article do |f| %>
    <%= render "editform", :f => f %>
  <% end %>
<% else %>
  <%# Not logged in or not privileged enough to edit an article %>
  <h1>Seis!</h1>
  Sinulla ei ole oikeutta muokata artikkeleja.
  <% unless current_user %>
    Et ole <%= link_to "kirjautunut sisään", log_in_path %>.
  <% end %>
<% end %>

app/views/articles/index.html.erb
<div id="articles_container" data-clean="true">
  <% @articles.each do |article| %>
    <%= render "/articles/render", :article => article, :do_truncation => true %>
  <% end %>
</div>

<% if @cut %>
  <%= link_to "Lataa lisää", articles_more_path(:depth => @depth),
    { :class => "action load_more_articles", :remote => true } %>
<% end %>



<% if current_user && current_user.privileges >= User.priv_level_writer %>
  <br/><br/>
  <%= link_to "Luo uusi artikkeli", new_article_path, { class: "action" } %>
<% end %>

app/views/articles/new.html.erb
<h1>Uusi artikkeli</h1>
<%= form_for :article, url: articles_path do |f| %>
  <%= render "editform", :f => f %>
<% end %>

app/views/articles/show.html.erb
<h1>Katsele artikkelia
  <%= link_to "&#8626;".html_safe, articles_path + "#article" + @article.id.to_s %>
</h1>

<%= render "articles/render", :article => @article %>

<br/>

<%= link_to "&#8626; PALAA".html_safe, articles_path + "#article" + @article.id.to_s %>