config/routes.rb
Rails.application.routes.draw do
  

  get 'hello_world/index'

  root 'hello_world#index'
  
  get "kirjaudu" => "sessions#new", :as => "log_in"
  get "kirjaudu/ulos" => "sessions#destroy", :as => "log_out"
  get "rekisteröidy" => "users#new", :as => "sign_up"
  
  resources :users, :sessions
  
  get "articles/more" => "articles#more", :as => "articles_more"
  resources :articles do
    resources :comments
  end
  
  
  match 'telegram' => 'telegram#index', via: [:get, :post]
  get 'telegram/setup' => 'telegram#setup'
  get 'telegram/connect' => 'telegram#connect'
  get 'telegram/disconnect' => 'telegram#disconnect'
  get 'telegram/repair' => 'telegram#repair'
  
  
  

end

app/views/shared/_head.html.erb
<%
  def create_pagelink(text, target, thispage = false, trg = "_self")
    if(thispage)
      thisp = "thispage"
    else
      thisp = ""
    end
    
    return link_to text, target, { :class => thisp, :target => trg }
  end
%>
<div class="head_wrapper">
  <div class="head">
    <h1><%= @sitetitle %></h1>
    <hr>
    <%= create_pagelink "ETUSIVU", root_path, current_page?('/') %>
    <%= create_pagelink "ARTIKKELIT", articles_path,
      current_page?(controller: 'articles') %>
    <%= create_pagelink "LÄHDEKOODI &#x2197".html_safe,
      "https://github.com/ollpu/rails-testing/", false, "_blank" %>
  </div>
</div>
<br/>

app/views/shared/_userdisplay.html.erb
<div class="usrdisplay">
  <% unless current_user %>
    <%= link_to "REKISTERÖIDY", sign_up_path %>
    tai <%= link_to "KIRJAUDU SISÄÄN", log_in_path %>
  <% else %>
    <%= current_user.full_name %>
    &#8226; <%# That's a bullet character %>
    <%= link_to "KIRJAUDU ULOS", log_out_path %>
  <% end %>
</div>