config/routes.rb
Rails.application.routes.draw do
  

  get 'hello_world/index'

  root 'hello_world#index'
  
  get "kirjaudu" => "sessions#new", :as => "log_in"
  get "kirjaudu/ulos" => "sessions#destroy", :as => "log_out"
  get "rekisteröidy" => "users#new", :as => "sign_up"
  
  resources :users, :sessions
  
  get "articles/more" => "articles#more", :as => "articles_more"
  resources :articles do
    resources :comments
  end
  
  
  match 'telegram' => 'telegram#index', via: [:get, :post]
  get 'telegram/setup' => 'telegram#setup'
  get 'telegram/connect' => 'telegram#connect'
  get 'telegram/disconnect' => 'telegram#disconnect'
  get 'telegram/repair' => 'telegram#repair'
  
  
  

end

app/views/layouts/application.html.erb
<%
  @sitetitle = "Joku hieno sivusto"
  
  if @title.present?
    @headtitle = @title
  else
    @headtitle = @sitetitle
  end
%>
<!-- This page has been compiled by the Ruby on Rails framework.
     App: (C) Roope Salmi 2015
     Source-code available at https://github.com/ollpu/rails-testing -->
<!DOCTYPE html>
<html>
<head>
  <title><%= @headtitle %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name=viewport content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
  <%= google_webfonts_init({
    google: ['Open Sans', 'Lora', 'Inconsolata']
  }) %>
</head>
<body>


<div class="content">
  <%= render "shared/userdisplay" %>
  <%= render "shared/head" %>
  <% if notice.present? %>
    <p class="notice"><%= notice %></p>
  <% end %>
  
  <%= yield %>
  
  <div class="footer">
    <%=
      link_to "KÄYTTÄJIEN HALLINTA", users_path if
        current_user && current_user.privileges >= User.priv_level_admin
    %>
    &nbsp;&nbsp;
    <%=
      link_to "TELEGRAM-BOTTI", telegram_setup_path if current_user
    %>
  </div>
</div>

</body>
</html>